### ISSUE TITLE
URI Factory argument phpdoc

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/message-factory#19]
It currently says mixed. Shouldn't it be string|UriInterface instead?

**Comment by dbu** [comment]
https://github.com/php-http/message-factory/blob/master/src/UriFactory.php#L17
i guess so. then again, a special factory might be able to handle other things. 
its a question of flexibility vs portability of code. i think string|UriInterface makes more sense. if somebody needs that specialized factory, they can still do it as there are no strict typehints possible for mixed argument types.
