### ISSUE TITLE
Are the dependencies backwards

### ISSUE THREAD

**Issue by Nyholm** [php-http/message-factory#28]
This repo does only contain interfaces but it has a dependency on `php-http/message`. Shouldn't it be the other way around?

I believe `php-http/message` should depend on `php-http/message-factory`, maybe I have missed something.

**Comment by Nyholm** [comment]
No sorry... It was me that missread the dependencies. Everything is in order.

**Comment by sagikazarmark** [comment]
https://github.com/php-http/message/blob/master/composer.json#L16

I think it does.

**Comment by Nyholm** [comment]
Thank you.
