### ISSUE TITLE
relation to the Body abstraction introduced in the adapter

### ISSUE THREAD

**Issue by dbu** [php-http/message-factory#4]
https://github.com/php-http/adapter/pull/42 introduced the Body interface to abstract different HTTP message bodies.

imho, the MessageFactory is playing the same role as [HttpMethodsClient](https://github.com/php-http/adapter/blob/terminology/src/HttpMethodsClient.php) and thus should have the same arguments for the body. it will also simplify the `send` method implementation for PSR-7 compatible http clients as they can simply delegate to the factory.

@sagikazarmark said in the discussion on the adapter PR

> Actually the MessageFactory has nothing to do with the Client/Adapter thing. The MessageFactory 
> package has been built for PSR-7 and I would like to make it as small as possible.
> 
> However I see the reason behind why it would make sense to handle Body classes in the message 
> factory: some content might need custom headers. To solve this I am going to add a getContentHeaders > method to the Body interface.

**Comment by sagikazarmark** [comment]
Well, I have a few other reasons against it:
- Currently there are no coupling between the adapter and the message factory package. Even if it is not a hard dependency (no need to depend on the package), it is lazy coupling. Also, Message Factory can be used in any PSR-7 related scenario, where the adapter is not even close to be used.
- It is not that much code to implement the body usage logic, however it should have been duplicated in every message factory. I don't think it worth that "sacrifice" to implement the logic in the message factory and not the client.
- As said before, message factory is a pure PSR-7 helper library and as such I would like to preserve it like that.

The code required to use Bodies:

``` php
if ($body instanceof Body) {
    $headers = array_merge($body->getContentHeaders(), $headers);
    $body = $body->toStreamable();
}
```

After that the string|StreamInterface body can be passed to the MessageFactory.

**Comment by dbu** [comment]
okay, convinced :-) thanks for the clarification
